### PR TITLE
Fix race conditions in rmw_wait and map queries to clients

### LINKED ISSUE #152: [test_rclcpp] #101 test_services_cpp (test_rclcpp.TestTwoExecutables.test_services_cpp)
Failure

```bash
[test_services_client_cpp-2] [==========] Running 5 tests from 1 test suite.
[test_services_client_cpp-2] [----------] Global test environment set-up.
[test_services_client_cpp-2] [----------] 5 tests from test_services_client
[test_services_client_cpp-2] [INFO] [1712303353.082268953] [rmw_zenoh_cpp]: Successfully connected to a Zenoh router with id 3e37a66397bacb45b5938f4ad4063a8.
[test_services_server_cpp-1] [INFO] [1712303353.086031453] [rmw_zenoh_cpp]: Successfully connected to a Zenoh router with id 3e37a66397bacb45b5938f4ad4063a8.
[test_services_client_cpp-2] [ RUN      ] test_services_client.test_add_noreqid
[test_services_client_cpp-2] [       OK ] test_services_client.test_add_noreqid (109 ms)
[test_services_client_cpp-2] [ RUN      ] test_services_client.test_add_reqid
[test_services_client_cpp-2] [       OK ] test_services_client.test_add_reqid (2 ms)
[test_services_client_cpp-2] [ RUN      ] test_services_client.test_return_request
[test_services_client_cpp-2] [       OK ] test_services_client.test_return_request (5 ms)
[test_services_client_cpp-2] [ RUN      ] test_services_client.test_add_two_ints_defered_cb
[test_services_client_cpp-2] [       OK ] test_services_client.test_add_two_ints_defered_cb (2 ms)
[test_services_client_cpp-2] [ RUN      ] test_services_client.test_add_two_ints_defcb_with_handle
[test_services_server_cpp-1]   what():  failed to send response: Unable to find taken request. Report this bug., at /home/yadunund/ros2_rolling/src/rmw_alternative/rmw_zenoh_cpp/src/rmw_zenoh.cpp:2890, at /home/yadunund/ros2_rolling/src/ros2/rcl/rcl/src/rcl/service.c:400
```

### PR DESCRIPTION
**Pull request by Yadunund**
Fixes https://github.com/ros2/rmw_zenoh/issues/152.

### CODE REVIEW

**Comment by Yadunund** [comment]
With the changes in this PR I am able to get `test_rclcpp` to pass

```bash
100% tests passed, 0 tests failed out of 118

Label Time Summary:
copyright      =   3.02 sec*proc (1 test)
cppcheck       =   0.39 sec*proc (1 test)
cpplint        =   1.09 sec*proc (1 test)
gtest          =  78.04 sec*proc (60 tests)
launch_test    = 214.65 sec*proc (52 tests)
lint_cmake     =   0.36 sec*proc (1 test)
linter         =   6.28 sec*proc (6 tests)
uncrustify     =   0.50 sec*proc (1 test)
xmllint        =   0.91 sec*proc (1 test)

Total Test time (real) = 299.03 sec

The following tests did not run:
	 28 - test_node_name__rmw_cyclonedds_cpp__rmw_zenoh_cpp (Skipped)
	 56 - test_node_name__rmw_fastrtps_cpp__rmw_zenoh_cpp (Skipped)
	 84 - test_node_name__rmw_fastrtps_dynamic_cpp__rmw_zenoh_cpp (Skipped)
	109 - test_node_name__rmw_zenoh_cpp__rmw_cyclonedds_cpp (Skipped)
	110 - test_node_name__rmw_zenoh_cpp__rmw_fastrtps_cpp (Skipped)
	111 - test_node_name__rmw_zenoh_cpp__rmw_fastrtps_dynamic_cpp (Skipped)

```

**Comment by Yadunund** [comment]
Well some tests seem to be flaky. Especially with exiting correctly. They seem to pass with 

```
colcon test --packages-select test_rclcpp --retest-until-pass 2
```

**Comment by clalancette** [comment]
> Well some tests seem to be flaky. Especially with exiting correctly. They seem to pass with

Yes, they are definitelly flaky.  When I did debugging on them, what I saw was that sometimes, a request was sent from the client, it was taken by the server, and the server sent a response, but that response never caused a callback to happen on the client.  It seems to be something in Zenoh proper, but I need to do a bit more debugging and speak to Zettascale people.

**Comment by clalancette** [comment]
Regardless, I think this is overall an improvement, so I'm going to go ahead and approve it (even though some of it is my own work).

**Review by clalancette — APPROVED** [review]

**Comment by Yadunund** [comment]
I'm seeing issues with the nav2 demo after merging this in. Specifically, the maps don't show up on RViz. I think it might be best if we split the changes here into 1) rmw_wait fixes and 2) map queries to clients.

**Pull request merged**
