### PR TITLE
Making clean code as per issue #855

### PR DESCRIPTION
**Pull request by shivangvijay**

### CODE REVIEW

**Comment by shivangvijay** [comment]
Can you share uncrustify config file (cfg file) with me or relevant parameters to set in default configuration file? Or is there any contributor guidelines document/checklist available?

**Comment by clalancette** [comment]
> Can you share uncrustify config file (cfg file) with me or relevant parameters to set in default configuration file? Or is there any contributor guidelines document/checklist available?

You'll need to follow the instructions at http://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html to get setup to run the tests successfully.

**Comment by shivangvijay** [comment]
After running ament_uncrustify --reformat, the issue was resolved. Upon checking both ament_uncrustify and ament_cpplint, they reported "No problems found." I believe the pipeline will now succeed.

**Review by clalancette — APPROVED** [review]
Thanks for the improvement!

**Pull request merged**
