### PR TITLE
test_rclcpp in ci

### PR DESCRIPTION
**Pull request by Yadunund**

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@Yadunund Could you please handle this issue? 
We decided to assign this issue to you at the latest waffle meeting. However, I don't have permission to change the Assignee field.

**Comment by Yadunund** [comment]
@CihatAltiparmak would you be willing to finish up what i started here? ie, follow-up #256 by updating the CI such that when it builds the Rolling source job, it also builds and tests `test_rclcpp`? The tricky part is getting the zenoh router to run in the github action along with the tests.

**Comment by CihatAltiparmak** [comment]
With a big pleasure. I was planning it as well. Seems like tricky part of Zenoh router is solved by 2 PRs so that tty was removed. I will start tomorrow.

**Comment by Yadunund** [comment]
> With a big pleasure. I was planning it as well. Seems like tricky part of Zenoh router is solved by 2 PRs so that tty was removed. I will start tomorrow.

Thanks so much!

**Comment by CihatAltiparmak** [comment]
Superseded by #271 Looks like zenoh router runs without problem. Seems like easier than i guess.

**Pull request closed without merging**
